version = '2'

[linters]
default = 'all'
disable = [
'wsl',
  'bodyclose',
  'contextcheck',
  'exhaustruct',
  'gomoddirectives',
  'gosmopolitan',
  'ireturn',
  'nilerr',
  'noctx',
  'nolintlint',
  'rowserrcheck',
  'sqlclosecheck',
  'staticcheck',
  'tparallel',
  'unparam',
  'unused',
  'wastedassign',
  'wrapcheck'
]

[linters.exclusions]
generated = 'lax'
presets = [
  'comments',
  'common-false-positives',
  'legacy',
  'std-error-handling'
]
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]

[formatters]
enable = [
  'gci',
  'gofmt',
  'gofumpt',
  'goimports'
]

[formatters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]
[linters.settings.depguard.rules.main]
files=['$all','!$test']
allow=['$gostd','github.com/xuender/helper']
